
services:

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "5000:5000/udp"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
      - ./scripts/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql

  frontend:
        build:
          context: ./frontend
        ports:
          - "3000:3000"
        restart: always
        depends_on:
          - backend
          - db
        environment:
          - VITE_BACKEND_URL=http://backend:8000

volumes:
  postgres_data:
