  services:
    backend:
      build:
        context: ./backend
      ports:
        - "8000:8000"
      restart: always

    frontend:
      build:
        context: ./frontend
      ports:
        - "3000:3000"
      restart: always
      depends_on:
        - backend
      environment:
        - VITE_BACKEND_URL=http://backend:8000
